### ISSUE TITLE
Code Solution Contradicts What the Task Asks For

### ISSUE THREAD

**Issue by Tellenwong** [learn-co-curriculum/dsc-generating-data-lab#3]
> That is:
> Create a classification dataset with 100 samples, 2 features, and 2 centers using make_blobs()
> Set random_state = 42 for reproducibility, and pass the appropriate value for cluster_std

Students are asked to set n_samples = 100, but the solution code shows n_samples = 200.

**Comment by lindseyberlin** [comment]
Fixed
